// Defines Sequelize models for SQL fallback. Returned models have similar names to mongoose ones.
module.exports = async function init(sequelize) {
  const { DataTypes } = require('sequelize');

  // Users table
  const User = sequelize.define('User', {
    name: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false, unique: true },
    passwordHash: { type: DataTypes.STRING, allowNull: false },
    role: { type: DataTypes.STRING, defaultValue: 'user' },
    themePreference: { type: DataTypes.STRING, defaultValue: 'light' }
  });

  // Pdf documents stored as plain text for search/chat; real systems would store binaries or S3 refs
  const PdfDocument = sequelize.define('PdfDocument', {
    filename: { type: DataTypes.STRING, allowNull: false },
    contentText: { type: DataTypes.TEXT('long') }
  });

  // Chat messages for PDF conversations
  const ChatMessage = sequelize.define('ChatMessage', {
    role: { type: DataTypes.STRING }, // 'user' or 'assistant'
    message: { type: DataTypes.TEXT }
  });

  // Reports generated by the system
  const Report = sequelize.define('Report', {
    title: { type: DataTypes.STRING, allowNull: false },
    content: { type: DataTypes.TEXT }
  });

  const Setting = sequelize.define('Setting', {
    preferences: { type: DataTypes.JSON }
  });

  // Associations
  User.hasMany(PdfDocument, { foreignKey: 'ownerId' });
  PdfDocument.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  PdfDocument.hasMany(ChatMessage, { foreignKey: 'pdfId' });
  ChatMessage.belongsTo(PdfDocument, { foreignKey: 'pdfId' });

  User.hasMany(Report, { foreignKey: 'ownerId' });
  Report.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  User.hasOne(Setting);
  Setting.belongsTo(User);

  await sequelize.sync();

  return { User, PdfDocument, ChatMessage, Report, Setting };
};
